// Package repo commits agent-generated code into a real git repository, one per
// project, so a codebase accumulates history across runs instead of being
// overwritten each time.
//
// Ported from synchro/app/utils/repo_writer.py, minus the container-specific
// path handling and with the silent-failure behaviour made explicit: callers
// get a non-nil error and can decide what to do.
package repo

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/synchro/synchro-cli/internal/model"
)

// Info describes a commit that was created.
type Info struct {
	Commit string
	Path   string
}

const (
	authorName  = "Synchro Developer Agent"
	authorEmail = "agents@synchro.local"
)

// git runs a git subcommand in dir and returns stdout.
func git(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	// Keep the agent's commits independent of the user's global config so a
	// missing user.name does not turn every run into a failure.
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME="+authorName,
		"GIT_AUTHOR_EMAIL="+authorEmail,
		"GIT_COMMITTER_NAME="+authorName,
		"GIT_COMMITTER_EMAIL="+authorEmail,
		// Never let a hook or a pager block a non-interactive run.
		"GIT_TERMINAL_PROMPT=0",
		"GIT_PAGER=cat",
	)
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return string(ee.Stderr), fmt.Errorf("git %s: %s", strings.Join(args, " "), strings.TrimSpace(string(ee.Stderr)))
		}
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return string(out), nil
}

// gitStaged returns how many paths git has staged for the next commit.
func gitStaged(dir string) (int, error) {
	// --cached diffs the index against HEAD, so this counts exactly what a
	// commit right now would record.
	out, err := git(dir, "diff", "--cached", "--name-only")
	if err != nil {
		return 0, err
	}
	n := 0
	for _, line := range strings.Split(out, "\n") {
		if strings.TrimSpace(line) != "" {
			n++
		}
	}
	return n, nil
}

// WriteFiles writes generated files into <reposDir>/<projectID>, initializing
// the repository on first use, then commits everything.
//
// A path escaping the repository is skipped rather than written: file content
// and paths both originate from a language model, so neither is trustworthy.
func WriteFiles(reposDir, projectID string, files []model.CodeFile, commitMsg string) (*Info, error) {
	if projectID == "" {
		return nil, fmt.Errorf("no project id")
	}
	if len(files) == 0 {
		return nil, nil
	}
	if _, err := exec.LookPath("git"); err != nil {
		return nil, fmt.Errorf("git is not installed or not on PATH: %w", err)
	}

	repoPath := filepath.Join(reposDir, projectID)
	isNew := false
	if _, err := os.Stat(filepath.Join(repoPath, ".git")); err != nil {
		isNew = true
	}
	if err := os.MkdirAll(repoPath, 0o755); err != nil {
		return nil, err
	}

	if isNew {
		if _, err := git(repoPath, "init", "-q", "-b", "main"); err != nil {
			// Older git does not know -b; retry without it.
			if _, err2 := git(repoPath, "init", "-q"); err2 != nil {
				return nil, err
			}
		}
		// A generated repo has no business inheriting the user's signing key.
		_, _ = git(repoPath, "config", "user.name", authorName)
		_, _ = git(repoPath, "config", "user.email", authorEmail)
		_, _ = git(repoPath, "config", "commit.gpgsign", "false")
	}

	root, err := filepath.Abs(repoPath)
	if err != nil {
		return nil, err
	}

	written := 0
	var skipped []string
	for _, f := range files {
		target := filepath.Join(root, filepath.FromSlash(f.Path))
		abs, err := filepath.Abs(target)
		if err != nil {
			skipped = append(skipped, f.Path)
			continue
		}
		rel, err := filepath.Rel(root, abs)
		if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			skipped = append(skipped, f.Path)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return nil, err
		}
		// Normalise line endings so generated files do not churn the whole
		// tree when checked out on a different platform.
		content := strings.ReplaceAll(f.Content, "\r\n", "\n")
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			return nil, err
		}
		written++
	}
	if written == 0 {
		if len(skipped) > 0 {
			return nil, fmt.Errorf("every generated path was outside the repository: %s", strings.Join(skipped, ", "))
		}
		return nil, nil
	}

	if _, err := git(repoPath, "add", "-A"); err != nil {
		return nil, err
	}
	// Ask git whether anything is actually staged. `git commit -q` reports
	// "nothing to commit" on stdout rather than stderr, so matching on the
	// error text is unreliable; asking first is exact.
	if staged, err := gitStaged(repoPath); err != nil {
		return nil, err
	} else if staged == 0 {
		// The model regenerated byte-identical files. That is a normal
		// outcome, not a failure, and the caller says so instead of
		// suggesting a commit.
		return nil, nil
	}
	if commitMsg == "" {
		commitMsg = "Agent update"
	}
	if _, err := git(repoPath, "commit", "-q", "-m", commitMsg); err != nil {
		// A concurrent change can still empty the index between the two
		// commands; treat that the same way.
		if strings.Contains(strings.ToLower(err.Error()), "nothing to commit") {
			return nil, nil
		}
		return nil, err
	}
	rev, err := git(repoPath, "rev-parse", "HEAD")
	if err != nil {
		return nil, err
	}
	return &Info{Commit: strings.TrimSpace(rev)[:12], Path: repoPath}, nil
}

// Log returns one line per commit, newest first, or nil if the project has no
// repository yet.
func Log(reposDir, projectID string, max int) []string {
	if projectID == "" || max <= 0 {
		return nil
	}
	repoPath := filepath.Join(reposDir, projectID)
	if _, err := os.Stat(filepath.Join(repoPath, ".git")); err != nil {
		return nil
	}
	out, err := git(repoPath, "log", fmt.Sprintf("-%d", max), "--pretty=format:%h %s")
	if err != nil || strings.TrimSpace(out) == "" {
		return nil
	}
	return strings.Split(strings.TrimSpace(out), "\n")
}

// ListFiles returns every file currently tracked in a project's repo, relative
// to the repo root, sorted.
func ListFiles(reposDir, projectID string) []string {
	if projectID == "" {
		return nil
	}
	repoPath := filepath.Join(reposDir, projectID)
	if _, err := os.Stat(filepath.Join(repoPath, ".git")); err != nil {
		return nil
	}
	out, err := git(repoPath, "ls-files")
	if err != nil {
		return nil
	}
	var files []string
	for _, l := range strings.Split(strings.TrimSpace(out), "\n") {
		if strings.TrimSpace(l) != "" {
			files = append(files, l)
		}
	}
	return files
}

// Show returns the contents of one file in a project's repo.
func Show(reposDir, projectID, relPath string) (string, error) {
	if projectID == "" {
		return "", fmt.Errorf("no project id")
	}
	repoPath := filepath.Join(reposDir, projectID)
	abs, err := safeJoin(repoPath, relPath)
	if err != nil {
		return "", err
	}
	b, err := os.ReadFile(abs)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func safeJoin(root, rel string) (string, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	abs, err := filepath.Abs(filepath.Join(absRoot, filepath.FromSlash(rel)))
	if err != nil {
		return "", err
	}
	r, err := filepath.Rel(absRoot, abs)
	if err != nil || r == ".." || strings.HasPrefix(r, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("path %q is outside the repository", rel)
	}
	return abs, nil
}
